Python update
mqlight/python-mqlight pull request #6
Opened 2017-01-10 13:48 UTC by ElliotGregory

These changes bring the mqlight python client upto the same level as the other clients.
There have been minor changes to the external API whereby some callback functions now include the client object.  Other changes include TSL support and extended parameter checking and unit test support.

2017-01-11 10:00 UTC, mimaison requested changes
Mostly nitpicks, thanks Elliot

2017-01-11 10:00 UTC, mimaison commented on docs/conf.py
> +# years="2013,2016"
Should the date be updated to 2017 ?

2017-01-11 10:00 UTC, mimaison commented on docs/sample.rst
> +                        SHARE_NAMEas the share name.
missing space

2017-01-11 10:00 UTC, mimaison commented on docs/sample.rst
> +                        mustbe secured with SSL/TLS
"mustbe" -> "must be"

2017-01-11 10:00 UTC, mimaison commented on docs/sample.rst
> +  MESSAGE               message to be sent (default: None)
As far as I can tell the send.py sample has not been changed and still sends "Hello world!" by default

2017-01-11 10:00 UTC, mimaison commented on tests/test_createclient.py
> +#            },
Is this commented out on purpose ?

2017-01-13 08:55 UTC, ElliotGregory commented on docs/sample.rst
> +                        SHARE_NAMEas the share name.
Has been corrected, thanks.

2017-01-13 08:56 UTC, ElliotGregory commented on docs/conf.py
> +# years="2013,2016"
I am leaving as 2016 as that was when the changes were made and built.

2017-01-13 08:56 UTC, ElliotGregory commented on docs/sample.rst
> +                        mustbe secured with SSL/TLS
Has been corrected, thanks.

2017-01-13 08:56 UTC, ElliotGregory commented on docs/sample.rst
> +  MESSAGE               message to be sent (default: None)
Has been corrected, thanks.

2017-01-13 08:57 UTC, ElliotGregory commented on tests/test_createclient.py
> +#            },
Comments remove and retested - no issues detected, thanks.

2017-01-13 10:26 UTC, mimaison approved these changes

2017-01-13 13:51 UTC, dnwe approved these changes

2017-01-13 14:15 UTC, dnwe commented
Thanks! Merged as 6137d85a59718de6dd4d16d6de254002345fe17a

2017-01-13 14:15 UTC, closed without merging